[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Убираем шум от Flask
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning

# Покрытие
addopts =
    -v
    --strict-markers
    --tb=short